@url = http://localhost:5104/api

GET {{url}}/people
Accept: application/json
Content-Type: application/json

###

GET {{url}}/people/1
Accept: application/json
Content-Type: application/json

###

POST {{URL}}/people
Accept: application/json
Content-Type: application/json
{
  "name":"Joenh Jr.",
  "sex":"M",
  "status": false
}

### 

PATCH {{URL}}/people/1
Accept: application/json
Content-Type: application/json
[
  {    
    "path": "/Status",
    "op": "replace",    
    "value": true
  }
]


